import {
  MILESTONE_TYPES,
  RESUME,
  STAYING_MOTIVATED,
  INTERVIEWING_SKILLS,
  PROFESSIONAL_NETWORK,
  RESEARCH_SKILLS,
  JOB_GOALS,
  SUPPORTING_INFORMATION,
  SOCIAL_NETWORK,
  STRENGTHS_AND_VALUES,
  STRESS_MANAGEMENT_PRACTICES,
} from './milestone-types';
import {
  FINDING_JOB,
  APPLYING_FOR_JOBS,
  TAKING_CARE,
  JOB_SEARCH_CATEGORIES,
  JOB_SEARCH_CATEGORY_COLORS,
} from './job-search-categories';

export {
  MILESTONE_TYPES,
  RESUME,
  STAYING_MOTIVATED,
  INTERVIEWING_SKILLS,
  FINDING_JOB,
  APPLYING_FOR_JOBS,
  TAKING_CARE,
  JOB_SEARCH_CATEGORIES,
  JOB_SEARCH_CATEGORY_COLORS,
  PROFESSIONAL_NETWORK,
  RESEARCH_SKILLS,
  JOB_GOALS,
  SUPPORTING_INFORMATION,
  SOCIAL_NETWORK,
  STRENGTHS_AND_VALUES,
  STRESS_MANAGEMENT_PRACTICES,
};
